[package]
authors = ["larry <gm@larry.engineer>", "PFC <pfc-validator@protonmail.com>"]
description = "Liquid staking protocol for the cosmos"
edition = "2018"
homepage = "https://steak.club"
license = "GPL-3.0-or-later"
name = "steak"
repository = "https://github.com/st4k3h0us3/steak-contracts"
version = "2.0.0"

[dependencies]
cosmwasm-std = "1.0"
osmo-bindings = {git = "https://github.com/apollodao/bindings.git"}
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
