[package]
authors = ["larry <gm@larry.engineer>", "PFC <pfc-validator@protonmail.com>"]
description = "Liquid staking protocol for the cosmos"
edition = "2018"
homepage = "https://steak.club"
license = "GPL-3.0-or-later"
name = "steak"
repository = "https://github.com/st4k3h0us3/steak-contracts"
version = "2.0.0"

[dependencies]
apollo-proto-rust = {branch = "master", git = "https://github.com/apollodao/apollo-proto-rust.git"}
apollo-protocol = {git = "https://github.com/apollodao/apollo-protocol.git", tag = "v0.11.3"}
cosmwasm-std = {version = "1.0.0", features = ["stargate"]}
cw-storage-plus = "0.13.4"
cw20 = "0.13.4"
cw20-base = "0.13.4"
prost = "0.10"
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}
cw-asset = {rev = "5f2fd3d15c18995e5ec0fdbc1456469a69edd4a4", git = "https://github.com/apollodao/cw-asset.git"}
